spring.datasource.url=jdbc:postgresql://localhost:5432/kutuphane
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Istanbul